apiVersion: v1
kind: Service
metadata:
  name: hello-python-service-orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  replicas: 2
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator-container
        image: eyacrfab.azurecr.io/samples/final_orchestrator:1.0
        ports:
        - containerPort: 5000
