apiVersion: v1
kind: Pod
metadata:
  name: {PodName}
spec:
  restartPolicy: Never
  containers:
  - image: python:3
    name: {ContainerName}
    command: ["python3"]
    args: ["{ScriptPath}/service.py"]
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
  volumes:
  - name: azure
    azureFile:
      secretName: azure-secret
      shareName: aksshare
      readOnly: false